service: skouppi

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - lambda:InvokeFunction
            - s3:*
            - comprehend:*
            - iam:PassRole
            # lisää tähän kaikki tarvittavat roolit, tsekkaa testi2:n käsin lisätyt roolit, myös lisätty trusted entity vai mikö olikaan
          Resource:
            #- "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"
            #- "arn:aws:lambda:${self:provider.region}"
            - "arn:aws:s3:::skouppi-classdata/*"
            - "arn:aws:s3:::skouppi-bucket/*"
            - "arn:aws:iam::235920682125:role/skouppi-sls-testi2-dev-us-east-1-lambdaRole"

functions:
  rssLambda:
    handler: rss-lambda/index.handler
    timeout: 10
    events:
      - eventBridge:
          schedule: rate(4 hours)

  dataggregatorLambda:
    handler: dataggregator-lambda/index.handler
    timeout: 20
    events:
      - s3:
          bucket: skouppi-classdata
          event: s3:ObjectCreated:*
          existing: true

  apiLambda: # muokkaa tää oikeaksi
    handler: api-lambda/index.handler
    timeout: 20
    events:
      - http:
          path: /uutiset
          method: GET
          cors: true

# resources:
#   Resources:

plugins:
  - serverless-ignore
